// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaH9cWksabaByimEiv1-DrgyVE1VfXyr8',
    appId: '1:872243096315:web:bfe0686004f7758b1b5e5e',
    messagingSenderId: '872243096315',
    projectId: 'restaurant-application-bc527',
    authDomain: 'restaurant-application-bc527.firebaseapp.com',
    storageBucket: 'restaurant-application-bc527.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8vyvt8VUc80EZChA09O7YgfYJUiCiL0k',
    appId: '1:872243096315:android:3c8b9b2cb620df9d1b5e5e',
    messagingSenderId: '872243096315',
    projectId: 'restaurant-application-bc527',
    storageBucket: 'restaurant-application-bc527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXtUuRrzIL_IzRDnTHEWqRIsHhz7fAMWs',
    appId: '1:872243096315:ios:e126660c0b880bd61b5e5e',
    messagingSenderId: '872243096315',
    projectId: 'restaurant-application-bc527',
    storageBucket: 'restaurant-application-bc527.appspot.com',
    iosBundleId: 'com.example.restaurantApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXtUuRrzIL_IzRDnTHEWqRIsHhz7fAMWs',
    appId: '1:872243096315:ios:e126660c0b880bd61b5e5e',
    messagingSenderId: '872243096315',
    projectId: 'restaurant-application-bc527',
    storageBucket: 'restaurant-application-bc527.appspot.com',
    iosBundleId: 'com.example.restaurantApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaH9cWksabaByimEiv1-DrgyVE1VfXyr8',
    appId: '1:872243096315:web:baeb20998461a8441b5e5e',
    messagingSenderId: '872243096315',
    projectId: 'restaurant-application-bc527',
    authDomain: 'restaurant-application-bc527.firebaseapp.com',
    storageBucket: 'restaurant-application-bc527.appspot.com',
  );

}